using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class csObjsInteract : MonoBehaviour
{
    // Obj ФнЖѓРЬДѕПЁ Player ФнЖѓРЬДѕАЁ enterЕШ УЄЗЮ ИЖПьНКИІ ХЌИЏ ObjАЁ PlayerОШПЁ ЕщОюАЈ ?
    // ИЖПьНК ХЌИЏ ЧиСІЧЯИщ ПјЛѓКЙБЭ ?
    //RaycastЗЮ ЙААЧ РЮНФШФ 'E'ХАИІ ДЉИЃИщ ФГИЏХЭ ОжДЯИоРЬМЧ РчЛ§, ЙААЧРК invokerepeatingЧдМіИІ РЬПыЧЯПЉ РкПЌНКЗЏПю РЇФЁ КЏАц, РЬШФ ЙААЧРЛ ФГИЏХЭРЧ РкНФРИЗЮ СіСЄЧЯПЉ ФГИЏХЭПЭ ЧдВВ ПђСїРЬЕЕЗЯЧд.

    Animator animator;
    private GameObject colObj;
    private GameObject ch;

    private bool isColliding = false;
    public bool isGrabbing = false;

    private GameObject Raydir;

    private Rigidbody rb;
    public float jumpPower = 10f;

    // Start is called before the first frame update
    void Start()
    {
        ch = gameObject;
        rb = GetComponent<Rigidbody>();
        animator = GetComponent<Animator>();
        Raydir = GameObject.FindGameObjectWithTag("RayDir");
        //Debug.Log(Vector3.Distance(ch.transform.position, Raydir.transform.position));
    }

    // Update is called once per frame
    void Update()
    {
        // RaycastИІ ХыЧи УцЕЙ УМХЉ
        Ray ray = new Ray(ch.transform.position + new Vector3(0, 0.2f, 0), (Raydir.transform.position - ch.transform.position).normalized);
        RaycastHit hit;

        if (Physics.Raycast(ray, out hit, 5f))
        {
            //Debug.DrawRay(ray.origin, ray.direction * hit.distance, Color.red, 0.7f);
            Debug.DrawRay(ch.transform.position + new Vector3(0, 0.2f, 0), (Raydir.transform.position - ch.transform.position).normalized, Color.red, 2f);
            // УцЕЙЧб ФнЖѓРЬДѕРЧ ХТБзАЁ "InteractiveObj"РЬИщ isCollidingРЛ trueЗЮ МГСЄ
            if (hit.collider.CompareTag("InteractiveObj"))
            {
                isColliding = true;
                colObj = hit.collider.gameObject;
            }
            else
            {
                isColliding = false;
                //colObj = null;
            }

        }
        else
        {
            isColliding = false;
            //colObj = null;
        }

        if (isGrabbing == false)
        {
            if (Input.GetKeyDown(KeyCode.E) && isColliding)
            {
                animator.SetTrigger("PickObj");
                Debug.Log("colliding");
                Invoke("inGrab", 0.5f);
            }
        }
        else
        {
            if (Input.GetKeyDown(KeyCode.E))
            {
                outGrab();
            }
            if (Input.GetKeyDown(KeyCode.Space))
            {
                Debug.Log("Jump");
                rb.AddForce(Vector3.up * jumpPower, ForceMode.Impulse);
            }
        }
    }

    void inGrab()
    {
        isGrabbing = true;
        Debug.Log("isGrabbing=true");
        animator.SetBool("Grabbing", isGrabbing);
        Vector3 newP = ch.transform.TransformPoint(Vector3.forward * 0.4f + Vector3.up * 0.2f);
        colObj.transform.position = newP;
        colObj.GetComponent<Rigidbody>().isKinematic = true;
        colObj.transform.parent = ch.transform;
        rb.constraints = rb.constraints | RigidbodyConstraints.FreezePositionX; // X ЦїСіМЧ ЧиСІ
        //rb.constraints = rb.constraints | RigidbodyConstraints.FreezePositionY;
        rb.constraints = rb.constraints | RigidbodyConstraints.FreezePositionZ;
    }

    void outGrab()
    {
        isGrabbing = false;
        Debug.Log("isGrabbing=false");
        animator.SetBool("Grabbing", isGrabbing);
        colObj.GetComponent<Rigidbody>().isKinematic = false;
        colObj.transform.parent = null;
        Debug.Log("КаИЎПЯЗс");
        rb.constraints = rb.constraints & ~RigidbodyConstraints.FreezePositionX; // X ЦїСіМЧ ЧиСІ
        //rb.constraints = rb.constraints & ~RigidbodyConstraints.FreezePositionY;
        rb.constraints = rb.constraints & ~RigidbodyConstraints.FreezePositionZ;
    }
}
